import openai_secret_manager

# Get API key for OpenAI
secrets = openai_secret_manager.get_secret("openai")
api_key = secrets["api_key"]

import openai
openai.api_key = api_key

# Function to detect AI-generated text
def detect_ai_text(text):
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=(f"Is this text generated by AI: {text}"),
        temperature=0.5
    )
    return response.choices[0].text

# Test the function
text = "AI-generated text example"
print(detect_ai_text(text))
